version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "1234:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  service0:
    build:
      context: ./service0
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=service0.local
      - VIRTUAL_PORT=80
